
------------------------------------------------------
--Create User
CREATE USER cardealership
    IDENTIFIED BY Pa55word
    DEFAULT TABLESPACE users
    TEMPORARY TABLESPACE temp
    QUOTA 10M ON users;

GRANT connect to cardealership;
GRANT resource to cardealership;
GRANT create session TO cardealership;
GRANT create table TO cardealership;
GRANT create view TO cardealership;

conn cardealership/Pa55word
------------------------------------------------------
--CAR TBL, SEQ, PRO
CREATE TABLE CAR_TBL(
CAR_ID NUMBER PRIMARY KEY,
CAR_OWNER NUMBER,
CAR_MODEL VARCHAR2(20),
CAR_YEAR NUMBER,
CAR_COLOR VARCHAR(20),
CAR_PRICE NUMBER
);

--DROP SEQUENCE CAR_SEQ;
CREATE SEQUENCE CAR_SEQ
  INCREMENT BY 1 MAXVALUE 5000 CYCLE;

CREATE OR REPLACE PROCEDURE INSERTCAR
(CAR_MODEL VARCHAR2, CAR_YEAR NUMBER, CAR_COLOR VARCHAR,CAR_PRICE NUMBER)
AS
BEGIN
    INSERT INTO CAR_TBL VALUES(CAR_SEQ.nextval,0, CAR_MODEL, CAR_YEAR, CAR_COLOR, CAR_PRICE);
    COMMIT;
END;
/
  
SELECT * FROM CAR_TBL;
-----------------------------------------------------------
--USER TBL, SEQ, PRO
CREATE TABLE USER_TBL(
USER_ID NUMBER PRIMARY KEY,
USER_USERNAME VARCHAR2(20),
USER_PASSWORD VARCHAR2(20),
USER_TYPE VARCHAR2(20)
);

CREATE SEQUENCE USER_SEQ
  INCREMENT BY 1 MAXVALUE 5000 CYCLE;

CREATE OR REPLACE PROCEDURE INSERTUSER
(USER_USERNAME VARCHAR2, USER_PASSWORD VARCHAR2, USER_TYPE VARCHAR2)
AS
BEGIN
    INSERT INTO USER_Tbl VALUES (USER_SEQ.NEXTVAL, USER_USERNAME,USER_PASSWORD,USER_TYPE);
    COMMIT;
END;
/

SELECT * FROM USER_TBL;
-----------------------------------------------------------
--PAYMENT TBL, SEQ, PRO
CREATE TABLE PAYMENT_TBL(
PAYMENT_ID INT PRIMARY KEY,
PAYMENT_VALUE NUMBER,
CONTRACT_ID INT
);

CREATE SEQUENCE PAYMENT_SEQ
  INCREMENT BY 1 MAXVALUE 5000 CYCLE;
  
CREATE OR REPLACE PROCEDURE INSERTPAYMENT
(PAYMENT_VALUE NUMBER, CONTRACT_ID NUMBER)
AS
BEGIN
    INSERT INTO PAYMENT_TBL VALUES(PAYMENT_SEQ.NEXTVAL,PAYMENT_VALUE,CONTRACT_ID);
    COMMIT;
END;
/
SELECT * FROM PAYMENT_TBL;
-----------------------------------------------------------
--OFFER TABLE, SEQ, PRO
CREATE TABLE OFFER_TBL(
OFFER_ID INT PRIMARY KEY,
CAR_ID NUMBER,
USER_ID NUMBER,
OFFER_DOWNPAYMENT NUMBER,
OFFER_TERMLOANLENGTH NUMBER,
OFFER_STATUS VARCHAR2(20)
);

CREATE SEQUENCE OFFER_SEQ
  INCREMENT BY 1 MAXVALUE 5000;
  
CREATE OR REPLACE PROCEDURE INSERTOFFER
(CAR_ID NUMBER, USER_ID NUMBER,  OFFER_DOWNPAYMENT NUMBER, OFFER_TERMLOANLENGTH NUMBER)
AS
BEGIN
    INSERT INTO OFFER_TBL VALUES(OFFER_SEQ.NEXTVAL, CAR_ID, USER_ID, OFFER_DOWNPAYMENT, OFFER_TERMLOANLENGTH, 'Pending');
    COMMIT;
END;
/

SELECT * FROM offer_tbl;
-----------------------------------------------------------
--CONTRACT TBL, SEQ, PRO
CREATE TABLE CONTRACT_TBL(
CONTRACT_ID INT PRIMARY KEY,
OFFER_ID NUMBER
);

CREATE SEQUENCE CONTRACT_SEQ
  INCREMENT BY 1 MAXVALUE 5000;
  
CREATE OR REPLACE PROCEDURE INSERTCONTRACT
(OFFER_ID NUMBER, DOWNPAYMENT NUMBER)
AS
BEGIN
    INSERT INTO CONTRACT_TBL VALUES(CONTRACT_SEQ.NEXTVAL,OFFER_ID);
    INSERT INTO PAYMENT_TBL VALUES(PAYMENT_SEQ.NEXTVAL,DOWNPAYMENT,CONTRACT_SEQ.CURRVAL);
    COMMIT;
END;
/

SELECT * FROM CONTRACT_TBL;
SELECT * FROM payment_tbl;